Turn down graphic settings when unfocused & improve Turkish language translation
juliand665/Dynamic-FPS pull request #96
Opened 2023-08-05 23:21 UTC by EuropaYou

Will resolve #54 

For now; turns off Entity Shadows, Smooth Lighting and clouds; Minimizes Particles; Sets Graphics to Fast.

Let me know if you want to add/remove features.

2023-08-06 09:37 UTC, LostLuma requested changes
Hello, thanks for the PR! Since this causes the entire world to reload every time the window is (un)focused I don't think this should be enabled by default, since the flashing from reloading and the resource usage jump on re-focusing is not expected of a resource saving mod IMO. Otherwise this looks good as-is I think :)

2023-08-06 09:38 UTC, LostLuma commented on src/main/java/dynamicfps/DynamicFPSConfig.java
> +	public boolean reduceGraphicsWhenUnfocused = true;
```suggestion
	public boolean reduceGraphicsWhenUnfocused = false;
```

2023-08-06 16:24 UTC, juliand665 commented
I wonder if it would make sense to separate out the settings changes that require a world reload into a separate setting? I assume fast graphics is the big one here.

2023-08-06 16:38 UTC, LostLuma commented
> I assume fast graphics is the big one here.

Both graphics and lighting quality changes cause the world to reload sadly.

I also got around to testing this now and looking at other options that could be useful, there's also the option to decrease entity distance when unfocused, which might be good to add to this PR either way but also to the non-reloading "safe" options to change list.

2023-08-07 01:17 UTC, LostLuma requested changes

2023-08-07 01:17 UTC, LostLuma commented on src/main/java/dynamicfps/DynamicFPSMod.java
> +
```suggestion
		if (config.fullyReduceGraphicsWhenUnfocused) {
			reduceGraphicsFully(gameOptions);
		}
		if (config.reduceGraphicsWhenUnfocused) {
			reduceGraphics(gameOptions);
		}
```

2023-08-07 01:17 UTC, LostLuma commented on src/main/java/dynamicfps/DynamicFPSMod.java
> +		increaseGraphics(gameOptions);
These methods can not be called unconditionally, as all of the `previousX` fields have not necessarily been initialized (or rather, are the default, so eg. boolean values are `false`) when the options are disabled, causing these options to be set to erroneous values.
```suggestion
		if (config.fullyReduceGraphicsWhenUnfocused) {
			increaseGraphicsFully(gameOptions);
		}
		if (config.reduceGraphicsWhenUnfocused) {
			increaseGraphics(gameOptions);
		}
```

2023-08-07 22:07 UTC, LostLuma commented
I'm not sure which bug you're referencing (unless it's the one I commented on in the last review, but that is solved now?), from my side this looks fine now. Please let me know if you'd still like to change something @EuropaYou.

2023-08-09 00:55 UTC, LostLuma approved these changes

2023-08-09 01:04 UTC, merged

2023-08-09 15:10 UTC, LostLuma commented
> Oh, I'm so sorry. I've been very busy the last two days.

No worries as I said!

> I also get these errors when the window regains focus:

Those are also caused by what I mentioned [in my last review](https://github.com/juliand665/Dynamic-FPS/pull/96#discussion_r1285295894). I assume you did not build the jar again with the two suggested commits included, meaning you don't have the fix. You can grab a [build from CI](https://github.com/juliand665/Dynamic-FPS/actions) instead if you'd like (a new proper release will still take a bit, have more PRs to write 🙂).